---
root: true

env:
  node: true

extends:
  - airbnb
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

overrides: []

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
  tsconfigRootDir: "./"

settings:
  import/resolver:
    typescript: {}

plugins:
  - '@typescript-eslint'

rules:
  eol-last: 0
  max-len:
    - error
    - 160
    - ignoreComments: true
  indent:
    - error
    - 2
    - SwitchCase: 1
  curly:
    - error
    - "all"
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: only-multiline
  operator-linebreak:
    - error
    - after
    - overrides:
        "?": before
        ":": before
